apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-akka-cluster-operator
  namespace: operators
spec:
  channel: stable
  name: akka-cluster-operator
  source: custom-catalog
  sourceNamespace: olm
